version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: ymirapp/wordpress-plugin
    versions:
    - 1.2.0
    - 1.2.1
  - dependency-name: wpackagist-plugin/akismet
    versions:
    - 4.1.8
    - 4.1.9
  - dependency-name: wpackagist-plugin/wp-mail-smtp
    versions:
    - 2.6.0
  - dependency-name: wpackagist-plugin/redirection
    versions:
    - 5.0.1
  - dependency-name: vlucas/phpdotenv
    versions:
    - 3.6.8
  - dependency-name: wpackagist-plugin/query-monitor
    versions:
    - 3.6.7
  - dependency-name: composer/installers
    versions:
    - 1.10.0
  - dependency-name: wpackagist-plugin/autodescription
    versions:
    - 4.1.3
