name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '8.0'
      - name: Install Ymir CLI
        run: composer global require ymirapp/cli
      - name: Deploy to production
        run: ymir deploy production
        env:
          YMIR_API_TOKEN: ${{ secrets.YMIR_API_TOKEN }}
